import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menu = [
  {
    labels : "Home",
    href : '/'
  },
  {
    labels : "ContactUs",
    href : '/contact-us'
  },
  {
    labels : "SignIn",
    href : '/login'
  }
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="px-[10%] bg-white shadow-lg sticky top-0 left-0 w-full py-6 flex justify-between items-center">
          <Link href="/" >Course App</Link>
          <div className="flex gap-16 items-center">{
             menu.map((item,idx)=>(
              <Link href={item.href} key={idx}>{item.labels}</Link>
             ))  
          }
          <Link href="/sign-up" className="py-2 px-4 bg-violet-600 rounded-md text-white">SignUp</Link>
          </div>
            
        </nav>
        <section>{children}</section>
        <footer>Welcome to Footer</footer>
      </body>
    </html>
  );
}
